export const WS_CONNECTION_START_ORDERS_ALL = 'WS_CONNECTION_START_ORDERS_ALL';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS'; 
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE'
export const  WS_CONNECTION_START_ORDERS_USER = 'WS_CONNECTION_START_ORDERS_USER';


export const wsActions = {
    wsInitOrdersAll: WS_CONNECTION_START_ORDERS_ALL,
    wsInitOrdersUser: WS_CONNECTION_START_ORDERS_USER,
    wsSendMessage: WS_SEND_MESSAGE,
    onOpen: WS_CONNECTION_SUCCESS,
    onClose: WS_CONNECTION_CLOSED,
    onError: WS_CONNECTION_ERROR,
    onMessage: WS_GET_MESSAGE
  };


