export const ingredients = [
    {
        calories: 420,
        carbohydrates: 53,
        fat: 24,
        image: "https://code.s3.yandex.net/react/code/bun-02.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
        name: "Краторная булка N-200i",
        price: 1255,
        proteins: 80,
        type: "bun",
        __v: 0,
        _id: "60d3b41abdacab0026a733c6"
    },
    {
        calories: 420,
        carbohydrates: 53,
        fat: 24,
        image: "https://code.s3.yandex.net/react/code/bun-02.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
        name: "Краторная булка N-200i",
        price: 1255,
        proteins: 80,
        type: "bun",
        __v: 0,
        _id: "60d3b41abdacab0026a733c6"
    },
    {
        calories: 99,
        carbohydrates: 42,
        fat: 24,
        image: "https://code.s3.yandex.net/react/code/sauce-03.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-03-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
        name: "Соус традиционный галактический",
        price: 15,
        proteins: 42,
        type: "sauce",
        __v: 0,
        _id: "60d3b41abdacab0026a733ce"
    },
    {
        calories: 14,
        carbohydrates: 11,
        fat: 22,
        image: "https://code.s3.yandex.net/react/code/sauce-04.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
        name: "Соус фирменный Space Sauce",
        price: 80,
        proteins: 50,
        type: "sauce",
        __v: 0,
        _id: "60d3b41abdacab0026a733cd"
    },
    {
        calories: 189,
        carbohydrates: 111,
        fat: 432,
        image: "https://code.s3.yandex.net/react/code/core.png",
        image_large: "https://code.s3.yandex.net/react/code/core-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
        name: "Кристаллы марсианских альфа-сахаридов",
        price: 762,
        proteins: 234,
        type: "main",
        __v: 0,
        _id: "60d3b41abdacab0026a733d2"
    },
    {
        calories: 14,
        carbohydrates: 11,
        fat: 22,
        image: "https://code.s3.yandex.net/react/code/sauce-04.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
        name: "Соус фирменный Space Sauce",
        price: 80,
        proteins: 50,
        type: "sauce",
        __v: 0,
        _id: "60d3b41abdacab0026a733cd"
    }
]